import {test} from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {projectAnchor,pickAt} from '../src/scene3d/Picking.ts';
import {cameraPreset,centers} from '../src/scene3d/cameraPresets.ts';
const camera=()=>{const c=new T.PerspectiveCamera(35,1,.1,50);c.position.set(0,0,6);c.lookAt(0,0,0);c.updateMatrixWorld(true);return c;};
const material=new T.MeshBasicMaterial({side:T.DoubleSide});
function mesh(z:number,id:string|null=null){const m=new T.Mesh(new T.BoxGeometry(.6,.6,.08),material);m.position.z=z;m.userData.interactionId=id;m.updateMatrixWorld(true);return m;}
test('front paper occludes interaction behind it',()=>{const back=mesh(0,'observe-noodle'),front=mesh(1);assert.equal(pickAt(0,0,camera(),[back,front]),null);front.visible=false;assert.equal(pickAt(0,0,camera(),[back,front]),'observe-noodle');});
test('hidden ancestors remove nested meshes from picking',()=>{const root=new T.Group(),nested=new T.Group(),m=mesh(0,'observe-mianwo');root.add(nested);nested.add(m);root.visible=false;root.updateMatrixWorld(true);assert.equal(pickAt(0,0,camera(),[m]),null);});
test('cutout paper opening does not grab a ray in empty space',()=>{const shape=new T.Shape();shape.moveTo(-1,-1);shape.lineTo(1,-1);shape.lineTo(1,1);shape.lineTo(-1,1);shape.closePath();const hole=new T.Path();hole.moveTo(-.45,-.45);hole.lineTo(-.45,.45);hole.lineTo(.45,.45);hole.lineTo(.45,-.45);hole.closePath();shape.holes.push(hole);const front=new T.Mesh(new T.ExtrudeGeometry(shape,{depth:.04,bevelEnabled:false}),material);front.userData.interactionId='cutout';front.updateMatrixWorld(true);const back=mesh(-1,'background-object');assert.equal(pickAt(0,0,camera(),[front,back]),'background-object');assert.equal(pickAt(.35,0,camera(),[front,back]),'cutout');});
test('projected anchor tracks viewport and hides when occluded',()=>{const object=mesh(0,'observe-noodle');const anchor={id:'observe-noodle',label:'罐',kind:'object' as const,shop:'noodle' as const,object,local:new T.Vector3(0,0,.09)};const a=projectAnchor(anchor,camera(),400,300,[object]);assert.ok(a.visible);assert.equal(a.x,200);assert.equal(a.y,150);const b=projectAnchor(anchor,camera(),800,600,[object]);assert.equal(b.x,a.x*2);assert.equal(b.y,a.y*2);assert.equal(projectAnchor(anchor,camera(),400,300,[object,mesh(1)]).visible,false);});
test('shop observation presets focus on the corresponding physical object',()=>{for(const id of ['noodle','doupi','mianwo'] as const){const normal=cameraPreset(id+'-shop',false);const close=cameraPreset(id+'-shop',false,0,true);assert.ok(close.position[2]<normal.position[2]);assert.notEqual(close.target[1],normal.target[1]);assert.ok(Math.abs(close.target[0]-centers[id])<2);}assert.ok(cameraPreset('mianwo-shop',false,0,true).target[1]<1);});
test('portrait street navigation focuses on each selected shop',()=>{for(let index=0;index<3;index++){const p=cameraPreset('past-street',true,index);assert.equal(p.target[0],centers[(['noodle','doupi','mianwo'] as const)[index]]);assert.match(p.id,/portrait/);}assert.notDeepEqual(cameraPreset('noodle-shop',true),cameraPreset('noodle-shop',false));});
