import * as T from 'three';
import {gsap} from 'gsap';
import {PaperFactory} from './PaperPart';
import {buildStage,type BuiltStage} from './ShopBuilder';
import {CameraRig,cameraPreset} from './CameraRig';
import {projectAnchor,pickAt} from './Picking';
export interface StageOptions {scene:string;expression:string;portraitIndex:number;observing:boolean;reduced:boolean;low:boolean;paused:boolean;portal:boolean;interactive:boolean}
export class PaperStage {
  renderer:T.WebGLRenderer;scene=new T.Scene();camera=new T.PerspectiveCamera(35,1,.1,90);rig:CameraRig;
  factory=new PaperFactory();built:BuiltStage|null=null;period='';options:StageOptions;token=0;disposed=false;lost=false;
  raf=0;lastTime=0;sun:T.DirectionalLight;size={w:1,h:1};buttons=new Map<string,HTMLButtonElement>();portalTween:gsap.core.Tween|null=null;
  constructor(public container:HTMLDivElement,public overlay:HTMLDivElement,public onInteract:(id:string)=>void,public onStatus:(state:string)=>void,public onPhoto:(url:string)=>void,options:StageOptions){
    this.options=options;this.renderer=new T.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true,powerPreference:'low-power'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.setClearColor('#e8dbc0');this.renderer.domElement.setAttribute('aria-label','武汉老街三维纸景');container.appendChild(this.renderer.domElement);this.rig=new CameraRig(this.camera);
    this.scene.background=new T.Color('#e8dbc0');this.scene.add(new T.HemisphereLight('#fff6dc','#b7a78a',2.5));this.sun=new T.DirectionalLight('#ffefcd',3.1);this.sun.position.set(-3,9,8);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);Object.assign(this.sun.shadow.camera,{left:-11,right:11,top:8,bottom:-6,near:.1,far:35});this.sun.shadow.bias=-.001;this.sun.shadow.normalBias=.035;this.scene.add(this.sun);this.sun.target.position.set(0,1,0);this.scene.add(this.sun.target);
    this.renderer.domElement.addEventListener('click',this.handleClick);this.renderer.domElement.addEventListener('webglcontextlost',this.handleLost);this.renderer.domElement.addEventListener('webglcontextrestored',this.handleRestored);document.addEventListener('visibilitychange',this.visibility);if(import.meta.env.DEV)document.addEventListener('paper-review-export',this.exportReview);this.resize();this.tick();
  }
  handleClick=(e:MouseEvent)=>{if(!this.options.interactive||this.options.portal||this.lost||this.options.paused)return;const b=this.renderer.domElement.getBoundingClientRect();const id=pickAt((e.clientX-b.left)/b.width*2-1,-((e.clientY-b.top)/b.height*2-1),this.camera,this.factory.meshes);if(id)this.onInteract(id);};
  handleLost=(e:Event)=>{e.preventDefault();this.lost=true;cancelAnimationFrame(this.raf);this.onStatus('context-lost');};
  handleRestored=()=>{if(this.disposed)return;this.lost=false;this.renderer.resetState();this.renderer.setClearColor('#e8dbc0');this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.shadowMap.enabled=!this.options.low;this.onStatus('ready');this.tick();};
  visibility=()=>{document.documentElement.classList.toggle('page-hidden',document.hidden);if(document.hidden)cancelAnimationFrame(this.raf);else if(!this.lost)this.tick();};
  resize(){const b=this.container.getBoundingClientRect();this.size={w:b.width,h:b.height};if(!b.width||!b.height)return;this.renderer.setSize(b.width,b.height);this.camera.aspect=b.width/b.height;this.camera.updateProjectionMatrix();this.applyCamera(false);}
  applyCamera(animate:boolean){const preset=cameraPreset(this.options.scene,this.size.h>this.size.w,this.options.portraitIndex,this.options.observing);this.rig.apply(preset,animate&&!this.options.reduced);this.container.dataset.camera=preset.id;}
  async update(options:StageOptions){const prior=this.options;this.options=options;this.sun.castShadow=!options.low;this.renderer.shadowMap.enabled=!options.low;this.renderer.setPixelRatio(Math.min(devicePixelRatio,options.low?1:1.5));const period=(options.scene.includes('present')&&!options.portal)?'present':'past';
    if(this.period!==period||!this.built){const run=++this.token;this.onStatus('loading');const factory=new PaperFactory();try{const built=await buildStage(factory,period,import.meta.env.BASE_URL+'assets/');if(this.disposed||run!==this.token){factory.dispose();return;}if(this.built)this.scene.remove(this.built.root);this.factory.dispose();this.factory=factory;this.built=built;this.scene.add(built.root);this.period=period;this.createButtons();this.applyCamera(false);this.scene.updateMatrixWorld(true);this.rig.update();this.renderer.render(this.scene,this.camera);this.onStatus('ready');this.container.dataset.parts=String(factory.records.length);if(period==='past')this.capturePhoto();}catch(error){factory.dispose();if(run===this.token){console.error(error);this.onStatus('failed');}}}
    else if(prior.scene!==options.scene||prior.observing!==options.observing||prior.portraitIndex!==options.portraitIndex)this.applyCamera(true);
    if(options.portal&&!this.portalTween&&this.built){for(const g of Object.values(this.built.shops)){g.scale.z=.22;g.position.z=-.4;}const p={v:0};this.portalTween=gsap.to(p,{v:1,duration:options.reduced?.4:3.4,ease:'power2.inOut',onUpdate:()=>{if(!this.built)return;for(const g of Object.values(this.built.shops)){g.scale.z=.22+p.v*.78;g.position.z=-.4+p.v*.4;}}});this.rig.camera.position.z+=3.5;this.applyCamera(true);if(import.meta.env.DEV&&location.search.includes('review=1'))[400,1200,2200,3200].forEach(ms=>setTimeout(()=>{if(!this.disposed&&this.options.portal)this.exportReview();},ms));}
    if(!options.portal&&this.built){this.portalTween?.kill();this.portalTween=null;for(const g of Object.values(this.built.shops)){g.scale.z=1;g.position.z=0;}}
    if(this.built)for(const id of ['noodle','doupi','mianwo'] as const){const m=this.built.owners[id].material as T.Material[];(m[0] as T.MeshStandardMaterial).map=this.built.ownerPrints[id][options.expression==='neutral'?0:1];}
  }
  capturePhoto(){if(!this.built)return;const oldP=this.camera.position.clone(),oldTarget=this.rig.target.clone(),oldAspect=this.camera.aspect,oldFov=this.camera.fov;const p=cameraPreset('past-street',false);this.rig.apply(p,false);this.camera.aspect=16/9;this.camera.updateProjectionMatrix();const target=new T.WebGLRenderTarget(960,540);target.texture.colorSpace=T.SRGBColorSpace;this.renderer.setRenderTarget(target);this.renderer.render(this.scene,this.camera);const pixels=new Uint8Array(960*540*4);this.renderer.readRenderTargetPixels(target,0,0,960,540,pixels);const c=document.createElement('canvas');c.width=960;c.height=540;const ctx=c.getContext('2d')!;const data=ctx.createImageData(960,540);for(let y=0;y<540;y++)data.data.set(pixels.subarray((539-y)*960*4,(540-y)*960*4),y*960*4);ctx.putImageData(data,0,0);this.photo=c.toDataURL('image/png');this.onPhoto(this.photo);this.renderer.setRenderTarget(null);target.dispose();this.camera.position.copy(oldP);this.rig.target.copy(oldTarget);this.camera.aspect=oldAspect;this.camera.fov=oldFov;this.camera.updateProjectionMatrix();this.rig.update();}
  photo='';
  exportReview=()=>{if(!import.meta.env.DEV||!this.built)return;this.renderer.render(this.scene,this.camera);const shop=this.options.scene.replace('-shop','');const name='paper-'+(['noodle','doupi','mianwo'].includes(shop)?shop:this.period==='past'?'street':'present')+(this.options.observing?'-observe':this.options.portal?'-portal_'+Math.round(this.built.shops.noodle.scale.z*100):'');const parts=this.factory.meshes.map((m,i)=>({...this.factory.records[i],position:m.position.toArray(),rotation:m.rotation.toArray().slice(0,3),scale:m.scale.toArray(),worldPosition:m.getWorldPosition(new T.Vector3()).toArray(),worldScale:m.getWorldScale(new T.Vector3()).toArray(),visible:m.visible}));void fetch(import.meta.env.BASE_URL+'__paper-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name+'-'+Math.round(innerWidth)+'x'+Math.round(innerHeight),image:this.renderer.domElement.toDataURL('image/png'),photo:this.photo,metrics:{scene:this.options.scene,camera:this.container.dataset.camera,position:this.camera.position.toArray(),target:this.rig.target.toArray(),parts,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio,canvas:[this.renderer.domElement.width,this.renderer.domElement.height]},anchors:this.built.anchors.map(a=>({id:a.id,world:a.object.localToWorld(a.local.clone()).toArray(),visible:this.buttons.get(a.id)?.style.display!=='none'})),renderers:1,drawCalls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles,lowPerformance:this.options.low,portal:{active:this.options.portal,depth:this.built.shops.noodle.scale.z}}})}).then(r=>{if(!r.ok)console.error('Review capture failed');});};
  createButtons(){this.buttons.forEach(b=>b.remove());this.buttons.clear();if(!this.built)return;for(const a of this.built.anchors){const b=document.createElement('button');b.className=a.kind==='shop'?'shop-entry shop-'+a.shop:'hotspot '+a.kind;b.dataset.anchor=a.id;b.setAttribute('aria-label',a.label);b.innerHTML=a.kind==='shop'?`<span class="shop-label">${a.label}</span><span class="shop-owner">走近聊聊 ↗</span>`:`<span class="hotspot-dot" aria-hidden="true">${a.kind==='person'?'“':a.kind==='object'?'+':'·'}</span><span class="hotspot-label">${a.label}</span>`;b.onclick=()=>{if(this.options.interactive&&!this.options.paused&&!this.options.portal)this.onInteract(a.id);};this.overlay.appendChild(b);this.buttons.set(a.id,b);}}
  tick=()=>{if(this.disposed||this.lost||document.hidden)return;this.raf=requestAnimationFrame(this.tick);const now=performance.now();if(now-this.lastTime<1000/(this.options.low?24:30))return;this.lastTime=now;this.rig.update();this.scene.updateMatrixWorld(true);
    if(this.built){for(const [index,g] of this.built.steam.entries()){g.visible=!this.options.low&&!this.options.reduced&&!this.options.paused;g.children.forEach(v=>{const t=((now/1000+(v.userData.phase??0)+index)%5)/5;v.position.y=t*.45;(v as T.Mesh<T.BufferGeometry,T.MeshBasicMaterial>).material.opacity=Math.sin(t*Math.PI)*.32;});}
      const current=this.options.scene.replace('-shop','');for(const a of this.built.anchors){const b=this.buttons.get(a.id)!;const active=this.options.scene.endsWith('-shop')?a.kind!=='shop'&&a.shop===current:this.options.scene==='past-street'?a.kind==='shop':false;const projected=projectAnchor(a,this.camera,this.size.w,this.size.h,this.factory.meshes);b.style.display=active&&this.options.interactive&&projected.visible&&!this.options.portal&&!this.options.observing?'':'none';b.style.left=projected.x+'px';b.style.top=projected.y+'px';b.dataset.world=projected.world.map(n=>n.toFixed(3)).join(',');}
    }
    this.renderer.render(this.scene,this.camera);this.container.dataset.drawCalls=String(this.renderer.info.render.calls);this.container.dataset.triangles=String(this.renderer.info.render.triangles);this.container.dataset.renderers='1';
  };
  dispose(){document.removeEventListener('paper-review-export',this.exportReview);this.disposed=true;++this.token;cancelAnimationFrame(this.raf);this.rig.cancel();this.portalTween?.kill();this.buttons.forEach(b=>b.remove());this.renderer.domElement.removeEventListener('click',this.handleClick);this.renderer.domElement.removeEventListener('webglcontextlost',this.handleLost);this.renderer.domElement.removeEventListener('webglcontextrestored',this.handleRestored);document.removeEventListener('visibilitychange',this.visibility);this.factory.dispose();this.sun.shadow.dispose();this.renderer.dispose();this.renderer.forceContextLoss();this.renderer.domElement.remove();}
}
