import * as T from 'three';
import {SVGLoader} from 'three/addons/loaders/SVGLoader.js';
export interface PartRecord {id:string;assetId:string;geometryType:string;position:number[];rotation:number[];scale:number[];thickness:number;frontMaterial:string;backMaterial:string;castShadow:boolean;receiveShadow:boolean;interactionId:string|null}
export class PaperFactory {
  textures=new Map<string,T.Texture>();materials=new Map<string,T.MeshStandardMaterial>();records:PartRecord[]=[];meshes:T.Mesh[]=[];
  paperTexture(type:string,color:string){const key=type+color;if(this.textures.has(key))return this.textures.get(key)!;const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d')!;x.fillStyle=color;x.fillRect(0,0,512,512);let seed=3721;const random=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};for(let i=0;i<4500;i++){x.fillStyle=i%2?'#fff8e816':'#45352812';x.fillRect(random()*512,random()*512,random()*2+.3,random()*2+.3);}x.strokeStyle='#4d3e2b45';x.lineWidth=2;
    if(type==='wood'){for(let i=0;i<6;i++){const y=90*i+12;x.beginPath();x.moveTo(0,y);x.bezierCurveTo(170,y-2,370,y+3,512,y);x.stroke();}x.lineWidth=1;for(let i=0;i<40;i++){const y=random()*512;x.beginPath();x.moveTo(random()*80,y);x.bezierCurveTo(190,y-5,350,y+6,500,y+1);x.stroke();}}
    if(type==='wall'){x.strokeStyle='#8d786930';for(let row=0;row<7;row++){let y=row*76;x.beginPath();x.moveTo(0,y);x.lineTo(512,y);for(let col=0;col<5;col++){const xx=col*120+(row%2?60:0);x.moveTo(xx,y);x.lineTo(xx,y+76);}x.stroke();}x.fillStyle='#fff9dd30';x.fillRect(40,35,95,24);x.fillRect(290,250,110,23);}
    if(type==='stone'){x.strokeStyle='#88786140';for(let i=0;i<7;i++){x.beginPath();x.moveTo(0,i*85);x.lineTo(512,i*85);x.moveTo(i*92,0);x.lineTo(i*92,512);x.stroke();}}
    if(type==='awning'){x.fillStyle='#f3e6cc28';for(let i=0;i<7;i++)x.fillRect(i*82,0,13,512);x.strokeStyle='#6a4b3533';for(let i=0;i<7;i++){x.beginPath();x.moveTo(i*82+17,0);x.lineTo(i*82+15,512);x.stroke();}}
    if(type==='roof'){x.strokeStyle='#352f2859';for(let i=0;i<9;i++){x.beginPath();x.moveTo(0,i*61);x.lineTo(512,i*61);for(let j=0;j<8;j++){x.moveTo(j*70+(i%2?35:0),i*61);x.lineTo(j*70+(i%2?35:0),(i+1)*61);}x.stroke();}}
    const map=new T.CanvasTexture(c);map.colorSpace=T.SRGBColorSpace;map.anisotropy=2;this.textures.set(key,map);return map;
  }
  material(type:string,color:string){const key=type+color;if(this.materials.has(key))return this.materials.get(key)!;const m=new T.MeshStandardMaterial({color:0xffffff,map:this.paperTexture(type,color),roughness:1,metalness:0});this.materials.set(key,m);return m;}
  add(parent:T.Group,id:string,geometry:T.BufferGeometry,material:T.Material|T.Material[],position:[number,number,number],thickness=.04,interactionId:string|null=null,assetId='procedural-paper'){
    const mesh=new T.Mesh(geometry,material);mesh.position.set(...position);mesh.name=id;mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData.interactionId=interactionId;parent.add(mesh);this.meshes.push(mesh);this.records.push({id,assetId,geometryType:geometry.type,position:[...position],rotation:[0,0,0],scale:[1,1,1],thickness,frontMaterial:Array.isArray(material)?'printed-front':'paper-print',backMaterial:'warm cream paper edge',castShadow:true,receiveShadow:true,interactionId});return mesh;
  }
  board(parent:T.Group,id:string,size:[number,number,number],position:[number,number,number],color='#d7c6a4',type='paper',interactionId:string|null=null){const key='atlas-'+type+color;let mat=this.materials.get(key);if(!mat){const c=document.createElement('canvas');c.width=1024;c.height=512;const ctx=c.getContext('2d')!;ctx.drawImage(this.paperTexture(type,color).image as CanvasImageSource,0,0,512,512);ctx.drawImage(this.paperTexture('paper','#f1e2c1').image as CanvasImageSource,512,0,512,512);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;this.textures.set(key,tex);mat=new T.MeshStandardMaterial({map:tex,roughness:1});this.materials.set(key,mat);}const geo=new T.BoxGeometry(...size),uv=geo.getAttribute('uv');for(let i=0;i<uv.count;i++){const face=Math.floor(i/4);uv.setX(i,uv.getX(i)*.5+(face===2||face===4?0:.5));}geo.clearGroups();return this.add(parent,id,geo,mat,position,Math.min(...size),interactionId);}
  shape(parent:T.Group,id:string,points:[number,number][],position:[number,number,number],color:string,thickness=.04,interactionId:string|null=null){const shape=new T.Shape();points.forEach(([x,y],i)=>i?shape.lineTo(x,y):shape.moveTo(x,y));shape.closePath();return this.add(parent,id,new T.ExtrudeGeometry(shape,{depth:thickness,bevelEnabled:false,steps:1}),[this.material('paper',color),this.material('paper','#f1e2c1')],position,thickness,interactionId);}
  async loadPrint(id:string,path:string){if(this.textures.has(id))return this.textures.get(id)!;const image=new Image();image.src=path;await image.decode();const tex=new T.Texture(image);tex.colorSpace=T.SRGBColorSpace;tex.needsUpdate=true;this.textures.set(id,tex);return tex;}
  card(parent:T.Group,id:string,d:string,print:T.Texture,width:number,height:number,position:[number,number,number],interactionId:string|null=null,sourceSize:[number,number]=[500,750]){
    const parsed=new SVGLoader().parse(`<svg xmlns="http://www.w3.org/2000/svg"><path d="${d}"/></svg>`);const shapes=SVGLoader.createShapes(parsed.paths[0]);const geo=new T.ExtrudeGeometry(shapes,{depth:.055,bevelEnabled:false,steps:1});geo.scale(width/sourceSize[0],-height/sourceSize[1],1);geo.translate(-width/2,height/2,0);const pos=geo.getAttribute('position'),uv=geo.getAttribute('uv');for(let i=0;i<pos.count;i++)uv.setXY(i,(pos.getX(i)+width/2)/width,(pos.getY(i)+height/2)/height);
    const front=new T.MeshStandardMaterial({map:print,color:'#ffffff',roughness:1,alphaTest:.45,side:T.DoubleSide});return this.add(parent,id,geo,[front,this.material('paper','#f4e7c7')],position,.055,interactionId,id);
  }
  text(parent:T.Group,id:string,text:string,width:number,height:number,position:[number,number,number],bg:string,ink='#49372c',fontSize=70){const c=document.createElement('canvas');c.width=1024;c.height=256;const ctx=c.getContext('2d')!;ctx.fillStyle=bg;ctx.fillRect(0,0,1024,256);ctx.strokeStyle='#674c3960';ctx.lineWidth=5;ctx.strokeRect(16,16,992,224);ctx.fillStyle=ink;ctx.font=`${fontSize}px "KaiTi", "Microsoft YaHei", serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,512,134);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;this.textures.set(id,tex);const m=new T.MeshStandardMaterial({map:tex,roughness:1});return this.add(parent,id,new T.BoxGeometry(width,height,.055),[this.material('paper','#f1e2c1'),this.material('paper','#f1e2c1'),this.material('paper','#f1e2c1'),this.material('paper','#f1e2c1'),m,this.material('paper',bg)],position,.055);}
  dispose(){const geometries=new Set<T.BufferGeometry>(),mats=new Set<T.Material>();for(const mesh of this.meshes){geometries.add(mesh.geometry);(Array.isArray(mesh.material)?mesh.material:[mesh.material]).forEach(m=>mats.add(m));}geometries.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());this.materials.forEach(m=>m.dispose());this.textures.forEach(t=>t.dispose());this.meshes=[];}
}
