import {useCallback,useEffect,useRef,useState,type CSSProperties} from 'react';
import {gsap} from 'gsap';
import {useStory} from './StoryProvider';
import {memoryCount} from './storyReducer';
import {dialogue,shops,shopIds,type ShopId} from '../content/story';
import {disclaimer,sources} from '../content/sources';
import {SceneStage,Steam,asset} from '../components/SceneStage';
import {DialoguePanel} from '../components/DialoguePanel';
import {Modal} from '../components/Modal';
import {photoPortal} from '../animation/photoPortal';
import {StoryAudio} from '../animation/audio';
import {lazy,Suspense} from 'react';
const ReviewPanel=import.meta.env.DEV?lazy(()=>import('../components/ReviewPanel').then(m=>({default:m.ReviewPanel}))):null;
type Overlay='sources'|'settings'|'memories'|'observe'|'food'|'reset'|'pause'|'invite'|'photo'|null;
let currentPhoto=asset('scenes/photo-front.png');
const detailNames={sauceJar:'saucejar',spatula:'spatula',stool:'stool'};
function BowlIcon(){return <svg viewBox="0 0 40 32" width="30" height="25" fill="none" aria-hidden="true"><path d="M4 13h32c-2 13-8 16-16 16S6 26 4 13Z" stroke="currentColor" strokeWidth="1.5"/><path d="M14 9c-6-5 4-5 0-9m10 9c-6-5 4-5 0-9" stroke="currentColor" strokeWidth="1.5"/></svg>;}
function Photo({className='',onClick,onPick,photoRef,back=false,active=false}:{className?:string;onClick?:()=>void;onPick?:()=>void;photoRef?:React.RefObject<HTMLDivElement|null>;back?:boolean;active?:boolean}) {
  const drag=useRef<{x:number;y:number}|null>(null);
  return <div ref={photoRef} className={'photo '+className+(back?' back':'')} data-photo>
    <div className="photo-border"/>
    {back?<div className="photo-back"><span className="small-label">相册里的一句留言</span><p>先坐下，<br/>吃口热的。</p><span className="tiny-label">署名不详 · 剧情创作</span></div>:<div className="photo-window"><img className="photo-image" src={currentPhoto} alt="原创纸景定格：三处早餐铺与摊前的小木凳" draggable={false}/>{active&&<Steam x={.33} y={.62}/>}</div>}
    <p className="photo-caption">武汉街巷清晨 / 纸景定格</p>
    {onClick&&<button className="photo-hit" aria-label="拿起照片" onClick={onClick} onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(drag.current&&Math.hypot(e.clientX-drag.current.x,e.clientY-drag.current.y)>38){drag.current=null;onPick?.();}}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}/>}
  </div>;
}
function Hotspot({position,label,kind,onClick,emphasis=false}:{position:[number,number];label:string;kind:string;onClick:()=>void;emphasis?:boolean}){return <button className={'hotspot '+kind+(emphasis?' first-hint':'')} style={{left:position[0]*100+'%',top:position[1]*100+'%'}} onClick={onClick}><span className="hotspot-dot" aria-hidden="true">{kind==='person'?'“':kind==='object'?'+':'·'}</span><span className="hotspot-label">{label}</span></button>;}
export function App(){
  const {state,dispatch,saveFailed}=useStory();const count=memoryCount(state);const shop=state.shopId?shops[state.shopId]:null;
  const [,setPhotoRevision]=useState(0);const [overlay,setOverlay]=useState<Overlay>(null);const overlayRef=useRef(overlay);overlayRef.current=overlay;
  const [exploring,setExploring]=useState(false);const [streetView,setStreetView]=useState(0);const [landscapeTip,setLandscapeTip]=useState(true);
  const [lifted,setLifted]=useState(false);const [settled,setSettled]=useState(false);const [running,setRunning]=useState(false);const runningRef=useRef(false);
  const [audioRejected,setAudioRejected]=useState(false);const [toast,setToast]=useState('');const photoRef=useRef<HTMLDivElement>(null);const portal=useRef<ReturnType<typeof photoPortal>|null>(null);const audio=useRef<StoryAudio|null>(null);
  const skipNextPop=useRef(false);
  const open=useCallback((value:Overlay)=>{if(!overlayRef.current)history.pushState({storyOverlay:true},'');setOverlay(value);},[]);
  const close=useCallback(()=>{setOverlay(null);if(history.state?.storyOverlay){skipNextPop.current=true;history.back();}},[]);
  useEffect(()=>{audio.current=new StoryAudio();audio.current.onRejected=()=>setAudioRejected(true);const onHide=()=>audio.current?.sync(audio.current.current,audio.current.settings,!!overlayRef.current);document.addEventListener('visibilitychange',onHide);return()=>{audio.current?.destroy();audio.current=null;document.removeEventListener('visibilitychange',onHide);};},[]);
  useEffect(()=>{audio.current?.sync(['past-street','shop','photo-return'].includes(state.screen)||running?'past':'present',state.settings,overlay==='pause');},[state.settings,state.screen,running,overlay]);
  useEffect(()=>{const onPop=()=>{if(skipNextPop.current){skipNextPop.current=false;return;}if(overlayRef.current){setOverlay(null);return;}if(runningRef.current){portal.current?.skip();return;}if(state.screen==='shop'){dispatch({type:'RETURN_STREET'});history.pushState({story:true},'');}else if(state.screen==='present-ending'||state.screen==='photo-return'){dispatch({type:'RESUME_PAST'});history.pushState({story:true},'');}else{open('pause');}};addEventListener('popstate',onPop);return()=>removeEventListener('popstate',onPop);},[state.screen,dispatch,open]);
  useEffect(()=>{if(state.screen!=='welcome'&&!history.state?.story)history.replaceState({story:true},'');},[state.screen]);
  useEffect(()=>{setExploring(false);setLifted(false);setSettled(false);if(state.screen!=='present-entry'){portal.current?.cancel();portal.current=null;setRunning(false);runningRef.current=false;}
    const timer=setTimeout(()=>{document.querySelector<HTMLButtonElement>(state.screen==='past-street'?'.shop-entry':'.dialogue button, .welcome button.primary')?.focus({preventScroll:true});},80);return()=>clearTimeout(timer);
  },[state.screen,state.shopId]);
  useEffect(()=>{const timer=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(timer);},[toast]);
  const previousCount=useRef(count);
  useEffect(()=>{if(count>previousCount.current&&shop)setToast('已记下 · '+shop.memory.title);previousCount.current=count;},[count,shop]);
  useEffect(()=>{if(count===3&&state.screen==='past-street'&&!state.invitationSeen){dispatch({type:'ACK_INVITATION'});open('invite');}},[count,state.screen,state.invitationSeen,open,dispatch]);

  useEffect(()=>{if(!lifted)return;const el=photoRef.current;if(!el)return;const t=gsap.fromTo(el,{y:120,rotation:-6,scale:.8},{y:0,rotation:-2,scale:1,duration:state.settings.reducedMotion?.2:1.2});const timer=setTimeout(()=>setSettled(true),state.settings.reducedMotion?250:2200);return()=>{t.kill();clearTimeout(timer);};},[lifted,state.settings.reducedMotion]);
  useEffect(()=>{const resize=()=>{if(runningRef.current)portal.current?.skip();};addEventListener('resize',resize);return()=>{removeEventListener('resize',resize);portal.current?.cancel();};},[]);
  const sound=()=>audio.current?.click();
  const unlock=()=>{audio.current?.unlock(state.settings);setAudioRejected(false);};
  const start=()=>{unlock();dispatch({type:'START'});};
  const pick=()=>{if(lifted||running)return;unlock();audio.current?.click(true);dispatch({type:'PICK_PHOTO'});setLifted(true);};
  const enterPast=(skip=false)=>{if(runningRef.current)return;runningRef.current=true;setRunning(true);const done=()=>{runningRef.current=false;setRunning(false);dispatch({type:'ENTER_PAST'});};if(skip){done();return;}if(photoRef.current)portal.current=photoPortal(photoRef.current,state.settings.reducedMotion,done);else done();};
  const goShop=(id:ShopId)=>{setStreetView(shopIds.indexOf(id));sound();dispatch({type:'ENTER_SHOP',shop:id});};
  const backdrop=state.screen==='shop'&&shop?shop.id+'-shop':['past-street','photo-return'].includes(state.screen)?'past-street':'present-street';
  const node=dialogue[state.dialogueNodeId];const endingReady=state.screen==='present-ending'&&node?.end.type==='ready';
  const showPhoto=state.screen==='present-entry'&&state.dialogueNodeId==='pick_photo';
  const memoryCard=(id:ShopId,interactive=false)=>{const s=shops[id],completed=state.completed[id];return <div key={id} className={'memory-entry '+(completed?'found':'unfound')}><span className="memory-number">0{shopIds.indexOf(id)+1}</span><div><span className="tiny-label">{s.name} · {completed?s.objectName:'仍有故事留在照片里'}</span><h3>{completed?s.memory.title:s.name+'的一个细节'}</h3><p>{completed?s.memory.text:'看看'+s.objectName+'，再问问'+s.owner+'。'}</p>{interactive&&<button className="text-button" onClick={()=>{close();dispatch({type:'RESUME_PAST'});dispatch({type:'ENTER_SHOP',shop:id});setExploring(!completed);}}>{completed?'回去重读':'去看看'} <span>↗</span></button>}</div></div>;};
  const reset=()=>{close();dispatch({type:'RESET'});setLifted(false);setRunning(false);};
  return <><main id="experience" className={'experience screen-'+state.screen+(state.settings.reducedMotion?' reduced-motion':'')}>
    <SceneStage scene={backdrop} expression={node?.expression} portraitIndex={streetView} observing={overlay==='observe'} portal={running} paused={!!overlay} interactive={['past-street','shop'].includes(state.screen)&&!overlay&&!running} onPhoto={url=>{currentPhoto=url;setPhotoRevision(n=>n+1);}} onInteract={id=>{
      if(state.screen==='past-street'&&id.startsWith('shop-'))goShop(id.slice(5) as ShopId);
      else if(state.screen==='shop'&&shop){if(id==='character-'+shop.id)setExploring(false);if(id==='observe-'+shop.id)open('observe');if(id==='food-'+shop.id)open('food');}
    }} onBack={()=>{if(state.screen==='shop')dispatch({type:'RETURN_STREET'});else open('pause');}}/>
    <div className="edge-shade" aria-hidden="true"/>
    <header className="topbar">
      {state.screen==='welcome'?<span className="brand"><BowlIcon/>味觉中国<span className="brand-divider"/>地方生活叙事</span>:<button className="nav-button" onClick={()=>{if(running){portal.current?.skip();return;}sound();if(state.screen==='shop')dispatch({type:'RETURN_STREET'});else if(['photo-return','present-ending'].includes(state.screen))dispatch({type:'RESUME_PAST'});else open('pause');}}>← <span>{state.screen==='shop'?'返回老街':['photo-return','present-ending'].includes(state.screen)?'再逛这条街':'暂停'}</span></button>}
      <nav>{state.screen!=='welcome'&&<button className="nav-button memory-button" onClick={()=>open('memories')}><BowlIcon/><span>我的过早</span><span className="count">{count} / 3</span></button>}<button className="nav-button sound-button" onClick={()=>{const value=!state.settings.muted;dispatch({type:'SET_SETTING',key:'muted',value});audio.current?.unlock({...state.settings,muted:value});setAudioRejected(false);}} aria-label={state.settings.muted?'开启声音':'静音'}>{state.settings.muted?'♪ ×':'♪'}</button><button className="nav-button" onClick={()=>open('settings')} aria-label="设置"><span aria-hidden="true">☷</span></button></nav>
    </header>
    {state.screen==='welcome'&&<><div className="welcome-photo"><Photo/><span className="photo-note">相册里，夹着一个清晨。</span></div><section className="welcome paper"><div className="welcome-kicker"><span className="small-label">武汉 · 日常的味道</span><span className="seal">过早</span></div><h1>过早<br/>旧影<span className="title-dot">。</span></h1><div className="ink-rule"/><p className="welcome-subtitle">走进一张照片，<br/>听见武汉的清晨。</p><div className="welcome-actions">{state.started?<><button className="primary" onClick={()=>{unlock();dispatch({type:'CONTINUE'});}}>继续这段清晨 <span>→</span></button><button className="text-button" onClick={()=>open('reset')}>重新开始</button></>:<button className="primary" onClick={start}>翻开这段清晨 <span>→</span></button>}</div><p className="duration">约 6—8 分钟 · 可以随时停留与继续</p><p className="disclaimer">{disclaimer}</p></section></>}
    {state.screen==='present-entry'&&!showPhoto&&<Photo className="entry-photo" back={state.dialogueNodeId==='intro_02'}/>}
    {showPhoto&&<><Photo className={'entry-photo '+(lifted?'lifted':'waiting')+(running?' portal-running':'')} photoRef={photoRef} onClick={!lifted?pick:undefined} onPick={pick} active={lifted}/><section className="photo-prompt paper">{!lifted?<><span className="small-label">家中相册 · 无署名</span><h2>先坐下，吃口热的。</h2><p>点一下照片，或把它轻轻拖起来。</p><button className="primary" onClick={pick}>拿起照片 <span>↑</span></button></>:running?<><p>清晨正在展开……</p><button className="text-button" onClick={()=>portal.current?.skip()}>跳过演出</button></>:<><span className="small-label">历史情境 · 约 1980 年代</span><h2>照片里的热气，动了。</h2><p>这条武汉街巷，似乎正在等你。</p><button className="primary" disabled={!settled} onClick={()=>enterPast()}>走进去 <span>→</span></button><button className="text-button" onClick={()=>enterPast(true)}>跳过演出</button></>}</section></>}
    {state.screen!=='welcome'&&!showPhoto&&!endingReady&&<DialoguePanel paused={!!overlay} exploring={exploring} onExplore={()=>setExploring(v=>!v)} onSound={sound}/>}
    {state.screen==='past-street'&&<><div className="street-actions"><button className="paper-chip" onClick={()=>count===3?dispatch({type:'VIEW_PHOTO'}):open('photo')}>再看看这张照片 ↗</button><button className="paper-chip" onClick={()=>dispatch({type:'RETURN_PRESENT'})}>回到今天 →</button></div><div className="portrait-street-nav"><button aria-label="看左边的店" disabled={streetView===0} onClick={()=>setStreetView(v=>Math.max(0,v-1))}>←</button><span>0{streetView+1} / 03 · {shops[shopIds[streetView]].name}</span><button aria-label="看右边的店" disabled={streetView===2} onClick={()=>setStreetView(v=>Math.min(2,v+1))}>→</button></div></>}
    {state.screen==='photo-return'&&<><Photo className="return-photo"/><div className="return-details">{shopIds.map(id=><figure key={id}><img src={asset('objects/'+detailNames[shops[id].object]+'.svg')} alt={shops[id].objectName}/><figcaption>{shops[id].objectName}</figcaption></figure>)}</div>{node?.end.type==='ready'&&<section className="photo-prompt paper"><span className="small-label">照片里的清晨</span><h2>它们把一段清晨，<br/>留在了街上。</h2><button className="primary" onClick={()=>dispatch({type:'RETURN_PRESENT'})}>回到今天 <span>→</span></button></section>}</>}
    {endingReady&&<section className="ending paper"><span className="small-label">今天 · 清晨仍在继续</span><h1>{count===3?'这张照片里的\n三段过早记忆':'还有一些故事，\n留在那条街里。'}</h1><p className="ending-quote">“坐下吃，还是带着走？”</p><div className="ending-memories">{shopIds.map(id=>memoryCard(id))}</div><div className="ending-buttons"><button className="primary" onClick={()=>dispatch({type:'RESUME_PAST'})}>{count===3?'再逛这条街':'继续探索'} <span>→</span></button><button className="text-button" onClick={()=>open('sources')}>查看资料</button><button className="text-button" onClick={()=>{dispatch({type:'WELCOME'});}}>回到开头</button></div><p className="tiny-label">三条作品记忆，不代表全部武汉饮食生活。</p></section>}
    <footer className="bottombar"><span>{state.screen==='welcome'?'一张照片 · 三间小铺 · 一个清晨':state.screen==='shop'?shop?.subtitle:['past-street','photo-return'].includes(state.screen)?'虚构街巷 · 情境演绎':'当代街口 · 三维纸景'}</span><button onClick={()=>open('sources')}>资料与创作说明 ↗</button></footer>
    {landscapeTip&&<div className="landscape-tip"><span>横屏观看，空间更完整</span><button aria-label="关闭横屏提示" onClick={()=>setLandscapeTip(false)}>×</button></div>}
    {saveFailed&&<p className="save-warning" role="status">本次进度暂未保存，仍可继续体验。</p>}
    {audioRejected&&<button className="audio-warning" onClick={()=>{unlock();dispatch({type:'SET_SETTING',key:'muted',value:false});}}>声音暂未开启 · 点此重试</button>}
    {toast&&<p className="toast paper" role="status">{toast}<span>收进“我的过早”</span></p>}
  </main>
  {overlay&&<Modal key={overlay} title={{sources:'资料与创作说明',settings:'让清晨按你的节奏',memories:'我的过早',observe:shop?.objectName??'观察旧物',food:shop?.name.replace(/[铺摊]/g,'')??'饮食小札',reset:'重新翻开这段清晨？',pause:'在这里，歇一会儿',invite:'再看看这张照片',photo:'相册里的清晨'}[overlay]} onClose={close} wide={overlay==='sources'||overlay==='memories'}>
    {overlay==='sources'&&<><p className="intro-note">{disclaimer}</p><div className="source-sections"><section><span className="small-label">创作层</span><h3>人物、照片与对白</h3><p>林姐、周师傅、陈伯及他们的师承与街坊关系均为虚构。照片为本作历史三维纸景的定格；“先坐下，吃口热的。”是创作留言，作者不详是剧情设定。人物对白不属于采访或历史引文。</p><p>约 1980 年代是情境范围，具体器具与服饰组合属于艺术设计。没有将本作街段命名为真实街道，也不宣称精确历史复原。</p></section><section><span className="small-label">归纳层</span><h3>三条文化记忆</h3><p>“日常节奏、手艺经验、街坊相处”是本作的主题表达。资料支持饮食知识；记忆签不是所有武汉居民的统一观点。</p></section></div><span className="small-label">资料层 · 2026-09-30 核查</span><div className="source-list">{sources.map(s=><article key={s.id}><span>{s.id}</span><div><a href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a><p className="tiny-label">{s.institution} · {s.date}</p><p>{s.scope}</p></div></article>)}</div><p className="intro-note">纸景的几何、纸面图案与轮廓纸偶为本项目原创程序及矢量美术，照片由同一纸景渲染生成，不是档案影像；声音为原创程序合成，无真人配音。文字使用系统中文字体，不附带付费字体。外部资料链接只作阅读入口，体验不依赖第三方图片。</p></>}
    {overlay==='settings'&&<div className="settings-list"><label><span><b>清晨的声音</b><small>轻环境与选择声，不影响文字剧情</small></span><input type="checkbox" checked={!state.settings.muted} onChange={e=>{dispatch({type:'SET_SETTING',key:'muted',value:!e.target.checked});audio.current?.unlock({...state.settings,muted:!e.target.checked});}}/></label><label><span><b>音量</b><small>{Math.round(state.settings.volume*100)}%</small></span><input aria-label="音量" type="range" min="0" max="1" step=".05" value={state.settings.volume} onChange={e=>dispatch({type:'SET_SETTING',key:'volume',value:Number(e.target.value)})}/></label><label><span><b>简化动效</b><small>减少蒸汽、人物呼吸，照片短淡入</small></span><input type="checkbox" checked={state.settings.reducedMotion} onChange={e=>dispatch({type:'SET_SETTING',key:'reducedMotion',value:e.target.checked})}/></label><label><span><b>低性能模式</b><small>降低像素比、关闭阴影和蒸汽，保留三维纸层</small></span><input type="checkbox" checked={state.settings.lowPerformance??false} onChange={e=>dispatch({type:'SET_SETTING',key:'lowPerformance',value:e.target.checked})}/></label><label><span><b>直接显示对白</b><small>关闭逐字显示，按你的速度阅读</small></span><input type="checkbox" checked={state.settings.instantText} onChange={e=>dispatch({type:'SET_SETTING',key:'instantText',value:e.target.checked})}/></label><p className="tiny-label">进度保存在本设备浏览器里。没有账号，也不上传个人照片。</p></div>}
    {overlay==='memories'&&<><p className="intro-note">已经记下 {count} 段清晨。故事不是考试，可以任意顺序停留。</p>{shopIds.map(id=>memoryCard(id,true))}{state.started&&<button className="primary" onClick={()=>{close();dispatch({type:'RESUME_PAST'});if(count===3)dispatch({type:'VIEW_PHOTO'});else dispatch({type:'RETURN_PRESENT'});}}>{count===3?'回望照片':'先回到今天'} <span>→</span></button>}</>}
    {overlay==='observe'&&shop&&<><p className="small-label live-observe-note">凑近看看这件旧物</p><p className="observation-text">{shop.detail}</p><blockquote><span>{shop.owner} · 创作对白</span>“{shop.reaction}”</blockquote>{shop.id==='mianwo'&&<div className="mini-photo-back">先坐下，吃口热的。<small>照片背面的创作留言</small></div>}<button className="primary" onClick={()=>{const fresh=!state.observed[shop.object];dispatch({type:'OBSERVE',object:shop.object});setExploring(false);close();if(fresh)setToast('刚才看到的……有了新的追问');}}>看完了，问问{shop.owner} <span>→</span></button></>}
    {overlay==='food'&&shop&&<><SafeDetail src={asset('objects/'+shop.id+'.svg')} alt={shop.name.replace(/[铺摊]/g,'')}/><p className="food-sensory">{shop.food.sensory}</p><p>{shop.food.text}</p><span className="small-label">饮食小札 · 资料说明</span><div className="fact-links">{shop.food.sourceIds.map(id=>{const s=sources.find(s=>s.id===id)!;return <a key={id} href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a>;})}</div><p className="tiny-label">当代整理的饮食特征，不证明本作虚构店铺的精确配方。</p></>}
    {overlay==='reset'&&<><p>这段故事的进度与文化记录会清空，声音和阅读设置保留。其他项目的本地记录不会受影响。</p><button className="primary" onClick={()=>{reset();dispatch({type:'START'});unlock();}}>确认重新开始 <span>→</span></button><button className="text-button" onClick={close}>保留这段清晨</button></>}
    {overlay==='pause'&&<><p>清晨不会催你。当前对白、观察与文化记录会留在这里。</p><button className="primary" onClick={close}>继续这段清晨 <span>→</span></button><button className="text-button" onClick={()=>{close();dispatch({type:'WELCOME'});}}>回到开头，保留进度</button><button className="text-button" onClick={()=>setOverlay('reset')}>重新开始</button></>}
    {overlay==='invite'&&<><p>一罐酱，一把旧工具，一张小凳子。照片还是这张照片，你却认出了更多东西。</p><button className="primary" onClick={()=>{close();dispatch({type:'VIEW_PHOTO'});}}>现在看看 <span>→</span></button><button className="text-button" onClick={close}>再逛一会儿</button></>}
    {overlay==='photo'&&<><Photo/><p>“先坐下，吃口热的。”</p><p>三间小铺还在照片里。看看一件旧物，听听一句招呼。</p></>}
  </Modal>}
  {ReviewPanel&&location.search.includes('review=1')&&<Suspense><ReviewPanel/></Suspense>}</>;
}
function SafeDetail({src,alt}:{src:string;alt:string}){const [failed,setFailed]=useState(false);const [attempt,setAttempt]=useState(0);return failed?<div className="detail-failed"><p>这张局部插画暂未加载。</p><button className="text-button" onClick={()=>{setFailed(false);setAttempt(n=>n+1);}}>重试插画</button></div>:<img className="detail-image" src={src+(attempt?'?retry='+attempt:'')} alt={alt} onError={()=>setFailed(true)}/>;}
