import {useState} from 'react';
import {useStory} from '../app/StoryProvider';
// Development-only controls. Vite removes the importer from the production bundle.
export function ReviewPanel(){const {state,dispatch}=useStory();const [message,setMessage]=useState('');const [shot,setShot]=useState('');return <aside style={{position:'fixed',right:0,top:76,width:94,maxHeight:280,overflow:'auto',zIndex:1000,background:'#fff7e5',padding:8,border:'1px solid #ab8e62',fontSize:9,maxWidth:94}} aria-label="开发验收">
  <input aria-label="截图标签" placeholder="截图标签" value={shot} onChange={e=>setShot(e.target.value.replace(/[^a-z0-9_]/g,''))} style={{width:76}}/>
  <button onClick={()=>{document.dispatchEvent(new CustomEvent('paper-review-export'));setMessage('样板已提交到本地验证目录');}}>保存纸景样板</button>
  <button onClick={async()=>{const {default:render}=await import('html2canvas');const canvas=await render(document.body,{scale:1,backgroundColor:'#f2e6cf',ignoreElements:el=>el.getAttribute('aria-label')==='开发验收',logging:false});const name='ui-'+(shot||state.dialogueNodeId)+'-'+innerWidth+'x'+innerHeight;const response=await fetch(import.meta.env.BASE_URL+'__paper-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,image:canvas.toDataURL('image/png'),metrics:{viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},state,overlay:document.querySelector('[role="dialog"]')?.getAttribute('aria-labelledby'),text:document.getElementById('experience')?.innerText,renderer:document.querySelector('[data-three-stage]')?.getAttribute('data-camera')}})});setMessage(response.ok?'页面截图已保存':'页面截图保存失败');}}>保存页面截图</button>
  <button onClick={()=>{const c=document.querySelector('canvas')!,gl=c.getContext('webgl2')!;const ext=gl.getExtension('WEBGL_lose_context');if(ext){ext.loseContext();setTimeout(()=>ext.restoreContext(),2300);setMessage('真实 WebGL 上下文丢失与恢复');}else setMessage('浏览器未提供测试扩展');}}>测试画面恢复</button>
  <button onClick={()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='wuhan-breakfast-story.save.v1')throw new DOMException('Test quota','QuotaExceededError');original.call(this,k,v);};dispatch({type:'SET_SETTING',key:'instantText',value:!state.settings.instantText});setMessage('只模拟本项目存储失败；刷新恢复');}}>测试存储失败</button>
  <small style={{display:'block'}}>当前节点 {state.dialogueNodeId} · 观察 {JSON.stringify(state.observed)} · 记录 {JSON.stringify(state.completed)}</small><small>{message}</small>
</aside>;}
